import React, { useEffect } from "react";
import type { AppProps } from "next/app";
import { GoogleFonts } from "nextjs-google-fonts/GoogleFonts";

import Head from "next/head";
// import Navbar from 'components/Navbar';
// import Footer from 'components/Footer';

// import 'bootstrap/dist/css/bootstrap.min.css';
import "styles/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "react-slideshow-image/dist/styles.css";

import "moment/locale/id.js";
import moment from "moment";

export default function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    const lang = localStorage.getItem("lang");

    if (!lang) {
      localStorage.setItem("lang", "id");
      moment.locale("id");
    } else {
      moment.locale(lang);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Narauction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-web.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <link rel="apple-touch-icon" href="/logo-web.png" />
        <link rel="manifest" href="/manifest.json" />
        {GoogleFonts()}
      </Head>
      {/* <Navbar /> */}
      <Component {...pageProps} />
      {/* <Footer /> */}
    </>
  );
}
